server:
  port: 8081
  servlet:
    context-path: /ums
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ums
    data-username: root
    data-password: monkey